# Generated by Django 5.0.3 on 2024-03-24 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppMusicy', '0004_remove_album_genre_remove_album_songs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='link',
            field=models.CharField(default='HPVJTT_h3nc', max_length=60),
        ),
    ]
